import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import NotificationCustom from "./NotificationCustom";
import SessionGuard from "./SessionGuard";
import AppLayout from "@/components/AppLayout";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "APstore",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NotificationCustom>
          <AppLayout>{children}</AppLayout>
        </NotificationCustom>
        <SessionGuard />
      </body>
    </html>
  );
}
